export const ADMIN_SERVICE_CONFIG = {
  BASE_ENDPOINT: "/api/admins",
  API_VERSION: "v1",
  OPERATION_TIMEOUT: 30000,
  RETRY_ATTEMPTS: 2,
  CACHE_ENABLED: true,
  AUDIT_ENABLED: true,
};

export const ERROR_TYPES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR",
  AUTH_ERROR: "AUTH_ERROR",
  PERMISSION_ERROR: "PERMISSION_ERROR",
  RATE_LIMIT_ERROR: "RATE_LIMIT_ERROR",
  SERVER_ERROR: "SERVER_ERROR",
};

export const OPERATION_TYPES = {
  READ: "READ",
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  SECURITY: "SECURITY",
  SYSTEM: "SYSTEM",
};
